name: Build Source Engine Manager

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish application
      run: dotnet publish SourceManager/SourceManager.csproj -c Release

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: source-engine-manager-exe
        path: SourceEngineManager/bin/Release/net8.0-windows/win-x64/publish/SourceManager.exe